apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifiap-api
  namespace: unifiappay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unifiap-api
  template:
    metadata:
      labels:
        app: unifiap-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: api
        image: YOUR_DOCKERHUB_USERNAME/unifiap-pay-api:latest
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: unifiap-api-svc
  namespace: unifiappay
spec:
  selector:
    app: unifiap-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: batch/v1
kind: Job
metadata:
  name: audit-job
  namespace: unifiappay
spec:
  template:
    spec:
      containers:
      - name: audit
        image: bitnami/kubectl:latest
        command: ["/bin/sh","-c","echo 'Audit run:'; date; kubectl get pods -n unifiappay --no-headers || true"]
      restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: unifiappay
spec:
  selector:
    matchLabels:
      name: log-collector
  template:
    metadata:
      labels:
        name: log-collector
    spec:
      containers:
      - name: log-collector
        image: busybox:1.36
        command: ["/bin/sh","-c","while true; do echo \"log-collector alive $(date)\"; sleep 60; done"]
        securityContext:
          runAsUser: 0
